# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'

pool:
  vmImage: $(imageName)

variables:
  ASAN_OPTIONS: detect_odr_violation=1

steps:
- script: cp Makefiles/sledconf.ci ./sledconf
  displayName: 'Prepare CI config'

- script: make
  displayName: 'Build'

- script: ./sled
  displayName: 'Test'